<a href="https://colab.research.google.com/github/divyanshusengar33/ML/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.  

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types


###Numpy Arrays Vs Python Sequences

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.  

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.  

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.  

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [63]:
#np.array(1d or vector)
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [64]:
#2D and 3d(matrix and tensor)
b = np.array([[1,2,3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [65]:
c = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [66]:
# To make float
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [67]:
#np.arange
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [68]:
#reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [69]:
#np.ones and np.zeros
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
#np.random
np.random.random((3,4))

array([[0.8611684 , 0.45724054, 0.33569246, 0.67925638],
       [0.67116457, 0.52951801, 0.69535431, 0.64333179],
       [0.08500118, 0.91093112, 0.32795764, 0.33685022]])

In [72]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [73]:
np.linspace(-10, 10, 10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [74]:
#np.identity
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###Array Attributes



In [75]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
#ndim
a3.ndim

3

In [77]:
#shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [79]:
#itemsize
a3.itemsize

8

In [80]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


###Changing Datatype


In [81]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

###Array Operations


In [82]:
a1 = np.arange(12).reshape(3,4)
a2 =np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
# scalar operation

#arthimetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [84]:
#relational
a2>5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [86]:
#vector operations
#arthimetic
a1 ** a2


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

###Array Functions


In [87]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 9., 80., 69.],
       [ 9.,  7., 38.],
       [ 3., 19., 70.]])

In [88]:
#max/min/sum/prod
# 0-> col and 1-> row
np.max(a1,axis=1)

array([80., 38., 70.])

In [89]:
np.min(a1)

np.float64(3.0)

In [90]:
np.sum(a1)

np.float64(304.0)

In [91]:
np.prod(a1)

np.float64(474546340800.0)

In [92]:
#mean/median/std/var
np.median(a1,axis =1)

array([69.,  9., 19.])

In [93]:
#trignometric funnction
np.sin(a1)

array([[ 0.41211849, -0.99388865, -0.11478481],
       [ 0.41211849,  0.6569866 ,  0.29636858],
       [ 0.14112001,  0.14987721,  0.77389068]])

In [94]:
#dot product
a2 =np.arange(12).reshape(3,4)
a3 =np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [95]:
#log and exponents
np.exp(a1)

array([[8.10308393e+03, 5.54062238e+34, 9.25378173e+29],
       [8.10308393e+03, 1.09663316e+03, 3.18559318e+16],
       [2.00855369e+01, 1.78482301e+08, 2.51543867e+30]])

In [96]:
#round/floor/cell
np.round(np.random.random((2,3))*100)

array([[94., 39., 21.],
       [68., 31., 36.]])

###Indexing and Slicing

In [97]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a1[-1]

np.int64(9)

In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a2[1,2]#row,column

np.int64(6)

In [102]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [103]:
a3[1,0,1]

np.int64(5)

In [104]:
a3[0,0,0]

np.int64(0)

In [105]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a1[2:5:2]

array([2, 4])

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [109]:
#1,3,9,11
a2[::2,1::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [110]:
a2[0,:]

array([0, 1, 2, 3])

In [111]:
a2[:,2]

array([ 2,  6, 10])

In [112]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [115]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [119]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
a3[0,1,:]

array([3, 4, 5])

In [122]:
a3[1,:,1]

array([10, 13, 16])

In [123]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [127]:
#0.2.18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

###Iterating


In [128]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
for i in a1:
  print(i)


0
1
2
3
4
5
6
7
8
9


In [129]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [130]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [137]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [139]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


###Reshaping

In [140]:
#Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [141]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

###Stacking

In [145]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [146]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [147]:
#vertical stack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###Spilitting

In [148]:
#horizontal spilitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [151]:
#vertical splitting


In [152]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [153]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]